chore: clean unused code and add `singleton` config to metrics task
infinilabs/framework pull request #17
Opened 2024-12-17 07:18 UTC by silenceqi

## What does this PR do
clean unused code 
add `singleton` config to metrics task

## Rationale for this change

## Standards checklist

- [ ] The PR title is descriptive
- [ ] The commit messages are [semantic](https://www.conventionalcommits.org/)
- [ ] Necessary tests are added
- [ ] Updated the release notes
- [ ] Necessary documents have been added if this is a new feature
- [ ] Performance tests checked, no obvious performance degradation

2024-12-17 08:23 UTC, medcl approved these changes

2024-12-17 08:24 UTC, medcl requested changes
Make sure you check and passed the `Standards checklist`

2024-12-17 10:10 UTC, luohoufu approved these changes

2024-12-18 02:45 UTC, silenceqi commented
> Make sure you check and passed the `Standards checklist`

Updated release notes

2024-12-19 03:57 UTC, medcl requested changes

2024-12-19 03:57 UTC, medcl commented on docs/content.en/docs/release-notes/_index.md
your release notes should place under `Latest (In development)`

2024-12-19 08:46 UTC, medcl approved these changes

2024-12-19 08:49 UTC, medcl requested changes

2024-12-19 08:49 UTC, medcl commented on docs/content.en/docs/release-notes/_index.md
> +### Features
Your release notes is quite confusing and i don't really get what you mean, can you rephrase the wording, can be easily fixed by using ChatGPT.

2024-12-20 00:46 UTC, medcl commented on docs/content.en/docs/release-notes/_index.md
>  ### Bug fix
why not resolve the rest of them?

2024-12-20 00:47 UTC, medcl approved these changes

2024-12-20 00:48 UTC, merged